# Generated by Django 5.1.3 on 2024-12-10 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_alter_profile_profile_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='profile_picture_public_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
