# Generated by Django 5.1.3 on 2024-12-10 05:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_profile_profile_picture_public_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='profile_picture_public_id',
        ),
    ]
