# Generated by Django 5.1.3 on 2024-12-14 11:54

import designSpace.accounts.validators
import functools
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_profile_first_name_profile_last_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='first_name',
            field=models.CharField(blank=True, max_length=30, null=True, validators=[functools.partial(designSpace.accounts.validators.validate_name, *(), **{'field_name': 'First name'})]),
        ),
        migrations.AlterField(
            model_name='profile',
            name='last_name',
            field=models.CharField(blank=True, max_length=30, null=True, validators=[functools.partial(designSpace.accounts.validators.validate_name, *(), **{'field_name': 'Last name'})]),
        ),
    ]
