# Generated by Django 5.1.3 on 2024-11-26 20:01

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('year', models.PositiveIntegerField()),
                ('area', models.PositiveIntegerField(blank=True, null=True)),
                ('location', models.CharField(max_length=100)),
                ('cover_image', models.ImageField(upload_to='project_images/')),
                ('image_library', models.ImageField(blank=True, null=True, upload_to='project_images/', validators=[django.core.validators.MaxValueValidator(10)])),
                ('description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
