# Generated by Django 5.1.3 on 2024-11-26 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='project_type',
            field=models.CharField(choices=[('residential', 'Residential Architecture'), ('commercial', 'Commercial Architecture'), ('institutional', 'Institutional Architecture'), ('religious', 'Religious Architecture'), ('cultural', 'Cultural Architecture'), ('landscape', 'Landscape Architecture'), ('urban_design', 'Urban Design'), ('sustainable', 'Sustainable Architecture'), ('transportation', 'Transportation Architecture'), ('interior', 'Interior Design'), ('modeling', '3D Modeling and Visualization'), ('other', 'Other')], default='other', max_length=20),
        ),
    ]
