# Generated by Django 5.1.3 on 2024-12-15 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_alter_project_cover_image_alter_projectimage_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='cover_image_public_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='projectimage',
            name='image_public_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
