# Generated by Django 5.1.3 on 2024-12-16 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('folders', '0001_initial'),
        ('projects', '0007_alter_projectimage_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='folders',
            field=models.ManyToManyField(blank=True, related_name='projects', to='folders.folder'),
        ),
    ]
