# Generated by Django 5.1.3 on 2024-12-18 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('folders', '0002_folder_projects'),
        ('projects', '0008_project_folders'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='folders',
            field=models.ManyToManyField(blank=True, related_name='projects_in', to='folders.folder'),
        ),
    ]
