# Generated by Django 5.1.3 on 2024-12-19 02:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0009_alter_project_folders'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='folders',
        ),
    ]
