# Generated by Django 5.1.3 on 2024-12-18 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('folders', '0001_initial'),
        ('projects', '0008_project_folders'),
    ]

    operations = [
        migrations.AddField(
            model_name='folder',
            name='projects',
            field=models.ManyToManyField(blank=True, related_name='folders_in', to='projects.project'),
        ),
    ]
